Models/ErrorViewModel.cs
namespace Endorsin.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using Endorsin.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Endorsin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/q1Controller.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace Endorsin.Controllers
{
    public class q1Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult profile()
        {
            return View();
        }

        public IActionResult company()
        {
            return View();
        }

        public IActionResult service()
        {
            return View();
        }

        public IActionResult collaboration()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Index";
}

<div class="full-container">
	
<div class="full-container" style="background-color:#E5B323;">
	<div class="container mx-auto p-5">
		<div id="home" class="row align-items-center">
		<div class="col">
			<p class="font-poppins fs-1 text-white">PROMOTE YOUR MSME WITH US</p>
			<p class="font-montserrat fs-3 text-black">Find thousands of influencers to promote your products easily and instantly</p>
			<a href="https://endorsin-client.000webhostapp.com/register" class="btn btn-primary">Register Now</a>
		</div>
		<div class="col">
			<img class="img-fluid" src="./assets/home-illustration.png" />
		</div>
	</div>
	</div>
	
</div>

<div class="full-container my-5">
	<h2 class="font-poppins text-center my-3">3 Easy Steps To Promote Your MSME</h2>
	<div class="container">
		<div id="box-steps" class="row">
		<div class="col p-2">
			<div class="bg-white shadow p-4">
				<img src="./assets/buat-campaign.png"/>
				<p class="font-raleway-bold fs-4 mt-3 text-black">Create a Campaign</p>
				<p class="font-raleway">Start creating a new campaign to explain your SME business and adjust the promotion budget according to your wishes.</p>
			</div>
		</div>
		<div class="col p-2">
			<div class="bg-white shadow p-4">
			<img src="./assets/pilih-influencer.png"/>
			<p class="font-raleway-bold fs-4 mt-4 text-black">Choose Influencers</p>
			<p class="font-raleway">Choose influencers based on our best recommendations. Communicate directly your MSME business brief.</p>
			</div>
		</div>
		<div class="col p-2">
			<div class="bg-white shadow p-4">
			<img src="./assets/pantau-hasil.png"/>
			<p class="font-raleway-bold fs-4 mt-3 text-black">Monitor Results</p>
			<p class="font-raleway">See how influencers are promoting your business and see the awareness performance you can get through the dashboard.</p>
			</div>
		</div>
	</div>
	</div>
	
</div>

<div class="full-container bg-white p-4">
	<h2 class="font-poppins text-center my-3">Reasons Why You Should Choose Us</h2>
	<div id="choose-us" class="row p-5 align-items-center">
		<div class="col">
			<p class="font-montserrat">We provide a variety of interesting features and conveniences for you to develop your MSME business to a higher level.</p>
			<div class="row">
				<div class="col-sm-1">
					<img class="img-fluid" src="./assets/badge-check.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat">Set the budget and promotion time according to your wishes</p>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-1">
					<img class="img-fluid" src="./assets/badge-check.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat">We provide recommendations for the best influencers that match your preferences</p>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-1">
					<img class="img-fluid" src="./assets/badge-check.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat">Monitor the success of your promotions in real time</p>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-1">
					<img class="img-fluid" src="./assets/badge-check.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat">Communicate directly the work you need with influencers.</p>
				</div>
			</div>
		</div>
		<div class="col">
			<img class="img-fluid" src="./assets/reason-choose-us.jpg"/>
		</div>
	</div>
</div>

<div class="full-container py-5">
	<h2 class="font-poppins text-center my-3">What do they think?</h2>
	<div class="container">
		<div id="box-testimonial" class="row">
		<div class="col p-2">
			<div class="bg-white shadow p-4">
			<p class="font-montserrat-italic text-center mb-2">“ Endorsin managed to meet me with the right influencers. I managed to increase the popularity of the MSME business as well as turnover by up to 20%. Thank you Endorsin. “</p>
			<div class="row p-2 mx-auto mt-4">
				<div class="col-4">
					<img class="img-fluid" src="./assets/testimonial-1.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat-bold mb-1">Dian Sastrowardoyo</p>
					<p class="font-montserrat">Katsu Chicken shop owner</p>
				</div>
			</div>
			</div>
		</div>
		<div class="col p-2">
			<div class="bg-white shadow p-4">
			<p class="font-montserrat-italic text-center mb-2">“ It is a pleasure to work with ENDORSIN, the service provided by ENDORSIN provides excellent service which makes us not encounter any significant difficulties in conducting promotions. “</p>
			<div class="row p-2 mx-auto mt-4">
				<div class="col-4">
					<img class="img-fluid" src="./assets/testimonial-2.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat-bold mb-1">Prilly Latuconsina</p>
					<p class="font-montserrat">Warteg Tegal Asli Owner</p>
				</div>
			</div>
			</div>
		</div>
		<div class="col p-2">
			<div class="bg-white shadow p-4">
			<p class="font-montserrat-italic text-center mb-2">“ Overall satisfy with Endorsin's performance that can connect my business with influencers. Plan and Monthly reports are detailed and insightful. Quick and fast in the execution of the given project. “</p>
			<div class="row p-2 mx-auto mt-4">
				<div class="col-4">
					<img class="img-fluid" src="./assets/testimonial-3.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat-bold mb-1">Nadeo Argawinata</p>
					<p class="font-montserrat">Anugerah Clothing Store Owner</p>
				</div>
			</div>
			</div>
		</div>
	</div>
	</div>
	
</div>


</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Endorsin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Endorsin.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Poppins:wght@400;700&family=Raleway:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-custom-yellow navbar-light px-5">
            <div class="container-fluid">
                <a class="text-brand navbar-brand font-raleway-bold" asp-area="" asp-controller="q1" asp-action="Index">Endorsin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="q1" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="q1" asp-action="profile">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="q1" asp-action="company">Company</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="q1" asp-action="service">Service</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="q1" asp-action="collaboration">Collaboration</a>
                        </li>
                        
                    </ul>
                    <ul class="navbar-nav ms-auto">
                            <li class="nav-item mx-2">
                                <a href="https://endorsin-client.000webhostapp.com/login" class="btn btn-outline-primary text-white">Login</a>
                            </li>
                            <li class="nav-item">
                                <a href="https://endorsin-client.000webhostapp.com/register" class="btn btn-primary">Sign Up</a>
                            </li>
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="full-container" style="background-color:#EFEFEF;">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            Endorsin Indonesia. All right reserved 2022.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/q1/Index.cshtml
@{
	ViewData["Title"] = "Index";
}

<div class="full-container">
	
<div class="full-container" style="background-color:#E5B323;">
	<div class="container mx-auto p-5">
		<div id="home" class="row align-items-center">
		<div class="col">
			<p class="font-poppins fs-1 text-white">PROMOTE YOUR MSME WITH US</p>
			<p class="font-montserrat fs-3 text-black">Find thousands of influencers to promote your products easily and instantly</p>
			<a href="https://endorsin-client.000webhostapp.com/register" class="btn btn-primary">Register Now</a>
		</div>
		<div class="col">
			<img class="img-fluid" src="./assets/home-illustration.png" />
		</div>
	</div>
	</div>
	
</div>

<div class="full-container my-5">
	<h2 class="font-poppins text-center my-3">3 Easy Steps To Promote Your MSME</h2>
	<div class="container">
		<div id="box-steps" class="row">
		<div class="col p-2">
			<div class="bg-white shadow p-4">
				<img src="./assets/buat-campaign.png"/>
				<p class="font-raleway-bold fs-4 mt-3 text-black">Create a Campaign</p>
				<p class="font-raleway">Start creating a new campaign to explain your SME business and adjust the promotion budget according to your wishes.</p>
			</div>
		</div>
		<div class="col p-2">
			<div class="bg-white shadow p-4">
			<img src="./assets/pilih-influencer.png"/>
			<p class="font-raleway-bold fs-4 mt-4 text-black">Choose Influencers</p>
			<p class="font-raleway">Choose influencers based on our best recommendations. Communicate directly your MSME business brief.</p>
			</div>
		</div>
		<div class="col p-2">
			<div class="bg-white shadow p-4">
			<img src="./assets/pantau-hasil.png"/>
			<p class="font-raleway-bold fs-4 mt-3 text-black">Monitor Results</p>
			<p class="font-raleway">See how influencers are promoting your business and see the awareness performance you can get through the dashboard.</p>
			</div>
		</div>
	</div>
	</div>
	
</div>

<div class="full-container bg-white p-4">
	<h2 class="font-poppins text-center my-3">Reasons Why You Should Choose Us</h2>
	<div id="choose-us" class="row p-5 align-items-center">
		<div class="col">
			<p class="font-montserrat">We provide a variety of interesting features and conveniences for you to develop your MSME business to a higher level.</p>
			<div class="row">
				<div class="col-sm-1">
					<img class="img-fluid" src="./assets/badge-check.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat">Set the budget and promotion time according to your wishes</p>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-1">
					<img class="img-fluid" src="./assets/badge-check.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat">We provide recommendations for the best influencers that match your preferences</p>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-1">
					<img class="img-fluid" src="./assets/badge-check.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat">Monitor the success of your promotions in real time</p>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-1">
					<img class="img-fluid" src="./assets/badge-check.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat">Communicate directly the work you need with influencers.</p>
				</div>
			</div>
		</div>
		<div class="col">
			<img class="img-fluid" src="./assets/reason-choose-us.jpg"/>
		</div>
	</div>
</div>

<div class="full-container py-5">
	<h2 class="font-poppins text-center my-3">What do they think?</h2>
	<div class="container">
		<div id="box-testimonial" class="row">
		<div class="col p-2">
			<div class="bg-white shadow p-4">
			<p class="font-montserrat-italic text-center mb-2">“ Endorsin managed to meet me with the right influencers. I managed to increase the popularity of the MSME business as well as turnover by up to 20%. Thank you Endorsin. “</p>
			<div class="row p-2 mx-auto mt-4">
				<div class="col-4">
					<img class="img-fluid" src="./assets/testimonial-1.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat-bold mb-1">Dian Sastrowardoyo</p>
					<p class="font-montserrat">Katsu Chicken shop owner</p>
				</div>
			</div>
			</div>
		</div>
		<div class="col p-2">
			<div class="bg-white shadow p-4">
			<p class="font-montserrat-italic text-center mb-2">“ It is a pleasure to work with ENDORSIN, the service provided by ENDORSIN provides excellent service which makes us not encounter any significant difficulties in conducting promotions. “</p>
			<div class="row p-2 mx-auto mt-4">
				<div class="col-4">
					<img class="img-fluid" src="./assets/testimonial-2.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat-bold mb-1">Prilly Latuconsina</p>
					<p class="font-montserrat">Warteg Tegal Asli Owner</p>
				</div>
			</div>
			</div>
		</div>
		<div class="col p-2">
			<div class="bg-white shadow p-4">
			<p class="font-montserrat-italic text-center mb-2">“ Overall satisfy with Endorsin's performance that can connect my business with influencers. Plan and Monthly reports are detailed and insightful. Quick and fast in the execution of the given project. “</p>
			<div class="row p-2 mx-auto mt-4">
				<div class="col-4">
					<img class="img-fluid" src="./assets/testimonial-3.png"/>
				</div>
				<div class="col">
					<p class="font-montserrat-bold mb-1">Nadeo Argawinata</p>
					<p class="font-montserrat">Anugerah Clothing Store Owner</p>
				</div>
			</div>
			</div>
		</div>
	</div>
	</div>
	
</div>


</div>

Views/q1/collaboration.cshtml
@{
	ViewData["Title"] = "Collaboration";
}

<div class="full-container">
	<div class="container-fluid bg-white">
		<div class="container mt-4">
			<h2 class="text-center font-poppins mb-4">Life at Endorsin</h2>
			<div class="container">
				<div id="life-endorsin" class="row align-items-center">
					<div class="col">
						<p class="font-montserrat fs-5">We open very wide opportunities for those of you who are interested in developing a career by joining Endorsin. With your help, let's make Endorsin the best digital marketing for MSME businesses in Indonesia.</p>
						<br/>
						<img class="float-start px-4" src="/assets/icons/mail.png"/>
						<p class="font-montserrat fs-5">endorsin@hrd.co.id</p>
						<br/>
						<img class="float-start px-4" src="/assets/icons/phone.png"/>
						<p class="font-montserrat fs-5">+62 878 1971 7584</p>
						<br/>
						<img class="float-start px-4" src="/assets/icons/instagram.png"/>
						<p class="font-montserrat fs-5">endorsin_indonesia</p>
						
					</div>
					<div class="col">
						<img class="img-fluid" src="/assets/vecteezy_brainstorming-process-concept-with-team-meeting_.jpg"/>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container p-4">
		<h2 class="font-poppins text-center">Be Our Partner</h2>
		<p class="font-montserrat text-center">Our mission would be difficult to achieve without your co-operative help. Be our partner and together we will advance MSMEs in Indonesia</p>
		<div class="container-md form-container border p-4 bg-white shadow font-montserrat">
			<form>
			  <div class="form-group mb-2">
				<label for="namaPerusahaan">Company name</label>
				<input type="text" class="form-control" id="namaPerusahaan" aria-describedby="namaPerusahaan" placeholder="Enter company name">
				</div>
			  <div class="form-group mb-2">
				<label for="emailPerusahaan">Company Email</label>
				<input type="email" class="form-control" id="emailPerusahaan" aria-describedby="emailPerusahaan" placeholder="Enter company email">
			  </div>
			  <div class="form-group mb-2">
				<label for="alamatPerusahaan">Address</label>
				<input type="text" class="form-control" id="alamatPerusahaan" aria-describedby="alamatPerusahaan" placeholder="Enter company address">
			  </div>
			  <div class="form-group mb-2">
				<label for="deskripsiPerusahaan">Description</label>
				<textarea class="form-control" id="deskripsiPerusahaan" rows="3" placeholder="Describe your company"></textarea>
			  </div>
			  <div class="form-check mb-3">
				<input type="checkbox" class="form-check-input" id="exampleCheck1">
				<label class="form-check-label" for="exampleCheck1">I agree to the applicable <a href="" class="text-primary">Terms & Conditions</a></label>
			  </div>
			  <button type="submit" class="btn btn-warning font-montserrat-bold text-white">Send</button>
			</form>
		</div>
	</div>
	<br/>
</div>

Views/q1/company.cshtml
@{
	ViewData["Title"] = "Company";
}

<div class="form-container">
	<div class="container-md text-center p-4">
		<h2 class="font-poppins">Meet Endorsin</h2>
		<p class="font-raleway fs-5">Endorsin is a digital influencer marketing platform based in Surabaya, Indonesia. We have a mission to increase the level of MSMEs in Indonesia through a digital promotion platform that works with influencers.</p>
	</div>

	<div class="container">
		<div class="card mb-3">
			<img class="card-img-top" src="/assets/company.png" alt="Card image cap">
			<div class="card-body">
				<h3 class="card-title text-center fs-2 font-montserrat-bold">Endorsin Office</h3>
				<p class="card-text text-center fs-5 font-montserrat">Kampus ITS Sukolilo, Jl. Teknik Kimia, Keputih, Kec. Sukolilo, Kota SBY, Jawa Timur 60111,<br />Indonesia</p>
			</div>
		</div>
	</div>

	<div class="container-md p-4">
		<div class="row justify-content-center">
			<div class="col-sm text-center">
				<p class="font-montserrat-bold fs-4">5678</p>
				<p class="font-montserrat fs-5">Number of Influencers</p>
			</div>
			<div class="col-sm text-center">
				<p class="font-montserrat-bold fs-4">2067</p>
				<p class="font-montserrat fs-5">Number of SMEs</p>
			</div>
			<div class="col-sm text-center">
				<p class="font-montserrat-bold fs-4">1034</p>
				<p class="font-montserrat fs-5">Ongoing Promotion</p>
			</div>
		</div>
	</div>

	<div class="container-fluid bg-white">
		<div class="container-md text-center p-4">
			<h2 class="font-poppins">Our Vision</h2>
			<p class="font-montserrat fs-4">Increasing the productivity of MSME actors and influencers in Indonesia</p>
			<br />
			<h2 class="font-poppins">Our Mission</h2>
			<ul class="list-misi text-start mx-auto fs-4">
				<li class="m-2">Providing a platform where MSMEs meet with influencers</li>
				<li class="m-2">Providing the best MSME promotion experience</li>
				<li class="m-2">Make it easy for influencers to get job endorsements</li>
				<li class="m-2">Connecting and providing security for promotional transactions between MSMEs and influencers</li>
			</ul>
		</div>
	</div>

</div>

Views/q1/profile.cshtml
@{
	ViewData["Title"] = "Profile";
}

<div class="full-container">
	<div class="container-md p-4 text-center">
		<h2 class="font-poppins">About Endorphin</h2>
		<p class="font-raleway fs-5 px-3">Endorsin is a digital influencer marketing platform based in Surabaya, Indonesia. We have a mission to increase the level of MSMEs in Indonesia through a digital promotion platform that works with influencers.</p>
	</div>

	<div class="container-fluid bg-white p-4">
		<div class="container">
			<h2 class="font-poppins text-center">Contact us</h2>
			<br/>
			<div class="container">
				<div id="box-profile" class="row align-items-center">
					<div class="col-md font-montserrat fs-6">
						<p>We love to interact with anyone. Please contact us if you have something to say, offer cooperation, or would like to be a part of Endorsin.</p>
						<br/>
						<div class="d-block mb-4">
							<img class="float-start px-4" src="/assets/icons/home.png"/>
							<p>Kampus ITS, Keputih, Kec. Sukolilo, Kota SBY, Jawa Timur</p>
						</div>
						<div class="d-block mb-4">
							<img class="float-start px-4" src="/assets/icons/mail.png"/>
							<p>endorsin@contact.co.id</p>
						</div>
						<div class="d-block mb-4">
							<img class="float-start px-4" src="/assets/icons/phone.png"/>
							<p>+62 895 3284 94336</p>
						</div>
						<div class="d-block mb-4">
							<img class="float-start px-4" src="/assets/icons/instagram.png"/>
							<p>endorsin_indonesia</p>
						</div>
					</div>
					<div class="col-md-7">
						<img class="img-fluid" src="/assets/contact.png"/>
					</div>
				</div>
			</div>
		</div>
		<br />
	</div>
	<br />
	<div class="container mt-4">
		<h2 class="font-poppins text-center">CEO & Founder Endorsin</h2>
		<div class="container mt-2">
			<div class="row align-items-center justify-content-center">
				<div class="col-md-4 my-4">
					<img class="img-fluid img-thumbnail border-light border-5 shadow" src="/assets/profil-ceo.jpg"/>
				</div>
				<div class="col-md-5">
					<h3 class="font-poppins">MOHAMAD KHOLID BUGHOWI</h3>
					<p class="font-raleway fs-5">An Infromatics Student from ITS</p>
					<p class="font-raleway fs-5">An organized and self motivated human with the vision to collaborate the ideas with touch of detail and creativity. Possess the boldness to make decisions and to deal with the challenges to reach his goals and objectives.</p>
					<img src="/assets/ttd-ceo.png"/>
					<div class="mt-5">
						<a href="https://web.facebook.com/muhammad.bugowy/" target="_blank" class="mx-3 text-decoration-none">
							<img class="img-fluid" src="/assets/icons/ceo-facebook.png"/>
						</a>
						<a href="https://www.instagram.com/muhammad_bughowy/" target="_blank" class="mx-3 text-decoration-none">
							<img class="img-fluid" src="/assets/icons/ceo-instagram.png"/>
						</a>
						<a href="https://www.linkedin.com/in/bughowi/" target="_blank" class="mx-3 text-decoration-none">
							<img class="img-fluid" src="/assets/icons/ceo-linkedin.png"/>
						</a>
						<a href="https://twitter.com/bughowy" target="_blank" class="mx-3 text-decoration-none">
							<img class="img-fluid" src="/assets/icons/ceo-twitter.png"/>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br />
	<br />
</div>

Views/q1/service.cshtml
@{
	ViewData["Title"] = "Service";
}

<div class="container-fluid">
	<div class="container p-4">
		<h2 class="font-poppins text-center mb-4">What we offer</h2>
		<p class="font-raleway text-center fs-5 px-5">Endorsin as a digital promotion platform, offers convenience for you MSME players throughout Indonesia to introduce your business to the public. In addition, Endorsin also facilitates influencers to obtain goods/services for them to endorse. We provide security guarantees to influencers and MSMEs during promotional activities.</p>
	</div>

	<div class="container mb-4">
		<h2 class="font-poppins text-center mb-4">For SMEs</h2>
		<div class="container">
			<div class="row justify-content-md-center mb-3">
				<div class="col-sm-4">
					<div class="bg-white shadow p-4">
						<img class="img-fluid mx-auto d-block mb-4" src="/assets/icons/icons8-minute-96.png"/>
						<p class="font-raleway-bold text-center">Save Your Time</p>
						<p class="font-raleway text-center">Save your precious time searching for influencers. We provide recommendations for the best influencers that match you</p>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="bg-white shadow p-4">
						<img class="img-fluid mx-auto d-block mb-4" src="/assets/icons/icons8-stack-of-money-96.png"/>
						<p class="font-raleway-bold text-center">Transparent Price</p>
						<p class="font-raleway text-center">The fees you pay are according to what you planned and are listed on your dashboard</p>
					</div>
				</div>
			</div>

			<div class="row justify-content-md-center">
				<div class="col-sm-4">
					<div class="bg-white shadow p-4">
						<img class="img-fluid mx-auto d-block mb-4" src="/assets/icons/icons8-tax-96.png"/>
						<p class="font-raleway-bold text-center">Money Back Guarantee</p>
						<p class="font-raleway text-center">We make sure your money will be returned if the influencer does not carry out the agreed endorsement task</p>
					</div>
				</div>
				<div class="col-sm-4"><div class="bg-white shadow p-4">
						<img class="img-fluid mx-auto d-block mb-4" src="/assets/icons/icons8-lock-96.png"/>
						<p class="font-raleway-bold text-center">Safe & Convenient</p>
						<p class="font-raleway text-center">We provide a sense of security and comfort as long as you join and grow your business with Endorsin</p>
					</div></div>
			</div>
		</div>
	</div>

	<br/>

	<div class="container">
		<h2 class="font-poppins text-center my-4">For Influencers</h2>
		<div class="container">
			<div id="box-umkm-1" class="row justify-content-md-center mb-3">
				<div class="col-sm-4">
					<div class="bg-white shadow p-4">
						<img class="img-fluid mx-auto d-block mb-4" src="/assets/icons/icons8-tv-program-96.png"/>
						<p class="font-raleway-bold text-center">Add Channel</p>
						<p class="font-raleway text-center">Add a variety of social media channels that you have and provide the best price offer for each channel.</p>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="bg-white shadow p-4">
						<img class="img-fluid mx-auto d-block mb-4" src="/assets/icons/icons8-new-job-96.png"/>
						<p class="font-raleway-bold text-center">Accept Job</p>
						<p class="font-raleway text-center">Receive and work directly on the endorsement task from MSMEs. Discuss directly the endorsement description with MSME owners.</p>
					</div>
				</div>
			</div>

			<div id="box-umkm-2" class="row justify-content-md-center">
				<div class="col-sm-4">
					<div class="bg-white shadow p-4">
						<img class="img-fluid mx-auto d-block mb-4" src="/assets/icons/icons8-man-holding-bags-with-money-96.png"/>
						<p class="font-raleway-bold text-center">Earn Money</p>
						<p class="font-raleway text-center">Send results and receive payments that go directly to your account balance from every endorsement that has been approved by the MSME owner.</p>
					</div>
				</div>
				<div class="col-sm-4"><div class="bg-white shadow p-4">
						<img class="img-fluid mx-auto d-block mb-4" src="/assets/icons/icons8-lock-96.png"/>
						<p class="font-raleway-bold text-center">Safe & Convenient</p>
						<p class="font-raleway text-center">We provide a sense of security and comfort as long as you join and develop your social media platform with Endorsin.</p>
					</div></div>
			</div>
		</div>
	</div>
</div>
<br/>